# Lines starting with # are comments
# package_name   # comment

# vim
vim
# vim-gnome  # vim with system clipboard support
exuberant-ctags

# c/c++
gcc
g++
make
cmake
gdb
ninja-build

# build deps
build-essential
linux-headers-`uname -r`

# python
python3
# python-dev  # YCM need
python3-dev

# fonts
fontconfig
fonts-wqy-microhei 
fonts-wqy-zenhei 
language-pack-zh-hans

# pyenv need
libssl-dev
zlib1g-dev
libbz2-dev
libreadline-dev
libsqlite3-dev
llvm
libncurses5-dev
libncursesw5-dev
xz-utils

zsh  # oh-my-zsh
# utils
curl   # transfer a url
# git
wget
ssh
zsh
# tmux
iputils-ping
# proxychains

# desktop (optional)
# fcitx input method
# fcitx
# fcitx-table-wbpy
# fcitx-config-gtk
# fcitx-frontend-all
# fcitx-ui-classic
# fcitx-module-kimpanel  # linuxmint need

# uget  # aria2 download manager
# aria2
# baobab  # disk usage
# gparted
# gnome-system-monitor
# shutter  # screenshot
# okular  # PDF reader
# vlc
# filezilla
# rdesktop  # RDP VNC client

