mklink /D "C:\Users\blueyi\AppData\Roaming\Mozilla\Firefox" "D:\blueyi\Firefox"
mklink /D "C:\Users\blueyi\Desktop" "D:\blueyi\Desktop"
mklink /D "C:\Users\blueyi\Documents" "D:\blueyi\Documents"
mklink /D "C:\Users\blueyi\Pictures" "G:\Pictures"
mklink /D "C:\Users\blueyi\Downloads" "G:\Downloads"
mklink /D "C:\Users\blueyi\Videos" "G:\Videos"
mklink /D "C:\Users\blueyi\Music" "G:\Music"
mklink "C:\Users\blueyi\.gitconfig" "D:\blueyi\.gitconfig"
mklink "C:\Users\blueyi\_vimperatorrc" "E:\GitHub\mylinux-misc\config\_vimperatorrc"
mklink "C:\Users\blueyi\_pentadactylrc" "E:\GitHub\mylinux-misc\config\_pentadactylrc"
mklink /D "C:\Users\blueyi\vimbak" "D:\blueyi\vimbak"
mklink /D "C:\Users\blueyi\.ssh" "D:\blueyi\.ssh"